name: Substance
version: 0.1.0-UNUSABLE
main: org.substancemc.core.SubstancePlugin
api-version: 1.20
author: SubstanceMC
description: Plugin to add lagfree custom entities to java vanilla minecraft
website: https://github.com/SubstanceMC
softdepend:
  - ProtocolLib